name: Size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Run size-limit
        uses: andresz1/size-limit-action@v1.7.0
        with:
          script: pnpm exec size-limit --json
          github_token: ${{ secrets.GITHUB_TOKEN }}
