name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run tests
        run: pnpm run coverage

      - name: Report coverage
        uses: codecov/codecov-action@v3
